services:
  backend:
    networks:
      - default
      - puglab_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yatzy.rule=Host(`yatzy.puglabz.com`)"
      - "traefik.http.routers.yatzy.entrypoints=web"
      - "traefik.http.services.yatzy.loadbalancer.server.port=3000"
      - "traefik.docker.network=puglab_default"
    environment:
      BETTER_AUTH_URL: https://yatzy.puglabz.com
      TRUSTED_ORIGINS: https://yatzy.puglabz.com,https://socket-io-lac.vercel.app

networks:
  puglab_default:
    external: true
