import { StyleSheet } from 'react-native';

export const COLORS = {
  background: '#F9F9F9',
  surface: '#FFFFFF',
  surfaceContainerLow: '#F3F4F4',
  primary: '#64578B',
  primaryContainer: '#D0C1FC',
  secondary: '#4B6550',
  secondaryContainer: '#D5F3D7',
  tertiary: '#81543B',
  tertiaryContainer: '#FEC2A2',
  onSurface: '#2F3334',
  onSurfaceVariant: '#5C6060',
  onSurfaceSubtle: '#9BA0A0',
  outlineVariant: '#AFB2B3',
};

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  contentArea: {
    flex: 1,
    minHeight: 0,
  },
  scrollView: {
    flex: 1,
  },
  scrollContentMobile: {
    paddingTop: 40,
    paddingHorizontal: 24,
    paddingBottom: 32,
  },
  scrollContentWeb: {
    paddingTop: 40,
    paddingHorizontal: 40,
    paddingBottom: 168,
  },
  heroCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    padding: 22,
    marginBottom: 14,
    shadowColor: '#2F3334',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 4,
  },
  eyebrow: {
    fontFamily: 'Inter_700Bold',
    fontSize: 11,
    letterSpacing: 4,
    color: COLORS.primary,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  titleHall: {
    fontFamily: 'Inter_700Bold',
    fontSize: 48,
    fontWeight: '800',
    lineHeight: 46,
    letterSpacing: -2,
    color: COLORS.onSurface,
  },
  titleFame: {
    fontFamily: 'Inter_700Bold',
    fontSize: 48,
    fontWeight: '800',
    lineHeight: 46,
    letterSpacing: -2,
    color: COLORS.tertiary,
  },
  tagline: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    lineHeight: 22,
    color: COLORS.onSurfaceVariant,
    marginTop: 10,
    maxWidth: 280,
  },
  shapesRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 12,
    marginTop: 16,
    marginBottom: 24,
  },
  shapeCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.primaryContainer,
  },
  shapeRect: {
    width: 32,
    height: 64,
    borderRadius: 8,
    backgroundColor: COLORS.secondaryContainer,
  },
  shapeWide: {
    width: 64,
    height: 32,
    borderRadius: 6,
    backgroundColor: COLORS.tertiaryContainer,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  refreshButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: COLORS.surfaceContainerLow,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  refreshText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 11,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: COLORS.onSurface,
  },
  updatedAt: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    color: COLORS.onSurfaceSubtle,
    marginBottom: 16,
  },
  cardList: {
    gap: 10,
  },
  mobileList: {
    gap: 12,
  },
  mobileCard: {
    backgroundColor: COLORS.surfaceContainerLow,
    borderRadius: 18,
    padding: 18,
    gap: 12,
    position: 'relative',
    overflow: 'hidden',
  },
  mobileCardGold: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.primaryContainer,
    shadowColor: '#2F3334',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 4,
  },
  mobileCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  mobileScoreRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
  },
  mobileScore: {
    fontFamily: 'Inter_700Bold',
    fontSize: 30,
    letterSpacing: -1.1,
    color: COLORS.tertiary,
  },
  rankPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORS.secondaryContainer,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  rankPillText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 11,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: COLORS.secondary,
  },
  playerName: {
    fontFamily: 'Inter_700Bold',
    fontSize: 18,
    letterSpacing: -0.4,
    color: COLORS.onSurface,
    flexShrink: 1,
    textAlign: 'right',
  },
  scoreLabel: {
    fontFamily: 'Inter_700Bold',
    fontSize: 10,
    letterSpacing: 3,
    textTransform: 'uppercase',
    color: COLORS.onSurfaceSubtle,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  statChip: {
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  statLabel: {
    fontFamily: 'Inter_700Bold',
    fontSize: 9,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: COLORS.onSurfaceSubtle,
  },
  statValue: {
    marginTop: 2,
    fontFamily: 'Inter_700Bold',
    fontSize: 14,
    letterSpacing: -0.2,
    color: COLORS.onSurface,
  },
  emptyCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 18,
    gap: 8,
  },
  emptyTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 16,
    color: COLORS.onSurface,
  },
  emptyText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    lineHeight: 20,
    color: COLORS.onSurfaceVariant,
  },
});
