import { StyleSheet } from "react-native";

export const COLORS = {
  background: "#F9F9F9",
  surface: "#FFFFFF",
  surfaceContainerLow: "#F3F4F4",
  primary: "#64578B",
  primaryContainer: "#D0C1FC",
  secondary: "#4B6550",
  secondaryContainer: "#D5F3D7",
  tertiary: "#81543B",
  tertiaryContainer: "#FEC2A2",
  onSurface: "#2F3334",
  onSurfaceVariant: "#5C6060",
  onSurfaceSubtle: "#9BA0A0",
  outlineVariant: "#AFB2B3",
};

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },

  desktopWrapper: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
  },
  desktopCard: {
    width: '100%',
    maxWidth: 560,
    maxHeight: '90%' as any,
    backgroundColor: COLORS.surface,
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#2F3334',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.08,
    shadowRadius: 48,
    elevation: 8,
  },
  desktopScroll: {
    paddingTop: 40,
    paddingHorizontal: 40,
    paddingBottom: 120,
  },

  scrollContent: {
    flexGrow: 1,
    paddingTop: 56,
    paddingHorizontal: 24,
    paddingBottom: 32,
  },

  eyebrow: {
    fontFamily: "Inter_700Bold",
    fontSize: 11,
    letterSpacing: 4,
    textTransform: "uppercase",
    color: COLORS.primary,
    marginBottom: 8,
    marginTop: 4,
  },
  titleVs: {
    fontFamily: "Inter_700Bold",
    fontSize: 72,
    fontWeight: "800",
    lineHeight: 66,
    letterSpacing: -3,
    color: COLORS.onSurface,
  },
  titleBot: {
    fontFamily: "Inter_700Bold",
    fontSize: 72,
    fontWeight: "800",
    lineHeight: 66,
    letterSpacing: -3,
    color: COLORS.tertiary,
  },
  tagline: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 22,
    color: COLORS.onSurfaceVariant,
    marginTop: 10,
    maxWidth: 260,
  },

  shapesRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 10,
    marginTop: 24,
    marginBottom: 32,
  },
  shapeCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primaryContainer,
  },
  shapeRect: {
    width: 26,
    height: 52,
    borderRadius: 6,
    backgroundColor: COLORS.secondaryContainer,
  },
  shapeWide: {
    width: 52,
    height: 26,
    borderRadius: 5,
    backgroundColor: COLORS.tertiaryContainer,
  },

  cardList: {
    gap: 10,
  },
  card: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 20,
    paddingHorizontal: 24,
    borderRadius: 16,
  },
  cardPrimary: {
    backgroundColor: COLORS.surface,
    shadowColor: "#2F3334",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 3,
  },
  cardSecondary: {
    backgroundColor: COLORS.surfaceContainerLow,
  },
  cardLeft: {
    gap: 4,
  },
  cardCode: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    letterSpacing: 3,
    textTransform: "uppercase",
    color: COLORS.onSurfaceSubtle,
  },
  cardLabel: {
    fontFamily: "Inter_700Bold",
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: -0.5,
    color: COLORS.onSurface,
    textTransform: "uppercase",
  },

  footerLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 32,
    opacity: 0.5,
  },
  footerDash: {
    width: 40,
    height: 1,
    backgroundColor: COLORS.outlineVariant,
  },
  footerText: {
    fontFamily: "Inter_700Bold",
    fontSize: 9,
    letterSpacing: 4,
    textTransform: "uppercase",
    color: COLORS.onSurfaceVariant,
  },

  resultContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  resultCard: {
    width: "100%",
    backgroundColor: COLORS.surface,
    borderRadius: 24,
    padding: 32,
    gap: 12,
    shadowColor: "#2F3334",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.07,
    shadowRadius: 32,
    elevation: 4,
  },
  resultIconRow: {
    alignItems: "center",
    marginBottom: 4,
  },
  resultTitle: {
    fontFamily: "Inter_700Bold",
    fontSize: 32,
    letterSpacing: -1,
    color: COLORS.onSurface,
    textAlign: "center",
  },
  resultDesc: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    color: COLORS.onSurfaceVariant,
    textAlign: "center",
    lineHeight: 22,
  },
  resultPrimaryButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 8,
  },
  resultPrimaryButtonText: {
    fontFamily: "Inter_700Bold",
    fontSize: 14,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "#FDF7FF",
  },
  resultSecondaryButton: {
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    backgroundColor: COLORS.surfaceContainerLow,
  },
  resultSecondaryButtonText: {
    fontFamily: "Inter_700Bold",
    fontSize: 13,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: COLORS.onSurfaceVariant,
  },
});
