import { StyleSheet } from "react-native";

export const COLORS = {
  background: "#F9F9F9",
  surface: "#FFFFFF",
  surfaceContainerLow: "#F3F4F4",
  primary: "#64578B",
  primaryContainer: "#D0C1FC",
  secondary: "#4B6550",
  secondaryContainer: "#D5F3D7",
  tertiary: "#81543B",
  tertiaryContainer: "#FEC2A2",
  onSurface: "#2F3334",
  onSurfaceVariant: "#5C6060",
  onSurfaceSubtle: "#9BA0A0",
  outlineVariant: "#AFB2B3",
};

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },

  scrollContent: {
    paddingTop: 56,
    paddingHorizontal: 24,
    paddingBottom: 140,
  },

  eyebrow: {
    fontFamily: "Inter_700Bold",
    fontSize: 11,
    letterSpacing: 4,
    textTransform: "uppercase",
    color: COLORS.primary,
    marginBottom: 8,
  },
  title: {
    fontFamily: "Inter_700Bold",
    fontSize: 52,
    lineHeight: 50,
    letterSpacing: -2,
    color: COLORS.onSurface,
  },
  titleAccent: {
    fontFamily: "Inter_700Bold",
    fontSize: 52,
    lineHeight: 50,
    letterSpacing: -2,
    color: COLORS.tertiary,
  },
  tagline: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 22,
    color: COLORS.onSurfaceVariant,
    marginTop: 14,
    maxWidth: 240,
  },

  shapesRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 10,
    marginTop: 24,
    marginBottom: 32,
  },
  shapeCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primaryContainer,
  },
  shapeRect: {
    width: 26,
    height: 52,
    borderRadius: 6,
    backgroundColor: COLORS.secondaryContainer,
  },
  shapeWide: {
    width: 52,
    height: 26,
    borderRadius: 5,
    backgroundColor: COLORS.tertiaryContainer,
  },

  cardList: {
    gap: 10,
  },
  card: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 20,
    paddingHorizontal: 24,
    borderRadius: 16,
  },
  cardPrimary: {
    backgroundColor: COLORS.surface,
    shadowColor: "#2F3334",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 3,
  },
  cardSecondary: {
    backgroundColor: COLORS.surfaceContainerLow,
  },
  cardLeft: {
    gap: 4,
    flex: 1,
  },
  cardCode: {
    fontFamily: "Inter_700Bold",
    fontSize: 10,
    letterSpacing: 3,
    textTransform: "uppercase",
    color: COLORS.onSurfaceSubtle,
  },
  cardLabel: {
    fontFamily: "Inter_700Bold",
    fontSize: 18,
    letterSpacing: -0.5,
    color: COLORS.onSurface,
    textTransform: "uppercase",
  },
  cardDesc: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    color: COLORS.onSurfaceVariant,
    marginTop: 2,
  },
  cardBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  cardBadgeEasy: {
    backgroundColor: COLORS.secondaryContainer,
  },
  cardBadgeMedium: {
    backgroundColor: COLORS.tertiaryContainer,
  },
  cardBadgeHard: {
    backgroundColor: COLORS.primaryContainer,
  },
  cardBadgeText: {
    fontFamily: "Inter_700Bold",
    fontSize: 14,
  },

  footerLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 32,
    opacity: 0.5,
  },
  footerDash: {
    width: 40,
    height: 1,
    backgroundColor: COLORS.outlineVariant,
  },
  footerText: {
    fontFamily: "Inter_700Bold",
    fontSize: 9,
    letterSpacing: 4,
    textTransform: "uppercase",
    color: COLORS.onSurfaceVariant,
  },

  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.surface,
    paddingTop: 12,
    paddingBottom: 28,
    paddingHorizontal: 24,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: "#2F3334",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 8,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: COLORS.surfaceContainerLow,
  },
  backButtonText: {
    fontFamily: "Inter_700Bold",
    fontSize: 13,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: COLORS.onSurface,
  },

  resultContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  resultCard: {
    width: "100%",
    backgroundColor: COLORS.surface,
    borderRadius: 24,
    padding: 32,
    gap: 12,
    shadowColor: "#2F3334",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.07,
    shadowRadius: 32,
    elevation: 4,
  },
  resultEmoji: {
    fontSize: 48,
    textAlign: "center",
    marginBottom: 4,
  },
  resultTitle: {
    fontFamily: "Inter_700Bold",
    fontSize: 32,
    letterSpacing: -1,
    color: COLORS.onSurface,
    textAlign: "center",
  },
  resultDesc: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    color: COLORS.onSurfaceVariant,
    textAlign: "center",
    lineHeight: 22,
  },
  resultPrimaryButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 8,
  },
  resultPrimaryButtonText: {
    fontFamily: "Inter_700Bold",
    fontSize: 14,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "#FDF7FF",
  },
  resultSecondaryButton: {
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    backgroundColor: COLORS.surfaceContainerLow,
  },
  resultSecondaryButtonText: {
    fontFamily: "Inter_700Bold",
    fontSize: 13,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: COLORS.onSurfaceVariant,
  },
});
