import { StyleSheet } from 'react-native';

export const COLORS = {
  background: '#F9F9F9',
  surface: '#FFFFFF',
  surfaceContainerLow: '#F3F4F4',
  surfaceContainer: '#ECEEEE',
  primary: '#64578B',
  primaryContainer: '#D0C1FC',
  secondary: '#4B6550',
  secondaryContainer: '#D5F3D7',
  tertiary: '#81543B',
  tertiaryContainer: '#FEC2A2',
  onSurface: '#2F3334',
  onSurfaceVariant: '#5C6060',
  onSurfaceSubtle: '#9BA0A0',
  outlineVariant: '#AFB2B3',
};

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  contentArea: {
    flex: 1,
    minHeight: 0,
  },
  scrollView: {
    flex: 1,
    minHeight: 0,
  },
  desktopWrapper: {
    flex: 1,
    minHeight: 0,
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingVertical: 40,
  },
  desktopCard: {
    width: '100%',
    maxWidth: 560,
    flex: 1,
    minHeight: 0,
    backgroundColor: COLORS.surface,
    borderRadius: 24,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#2F3334',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.08,
    shadowRadius: 48,
    elevation: 8,
  },
  desktopScroll: {
    paddingTop: 40,
    paddingHorizontal: 40,
    paddingBottom: 32,
  },
  scrollContentMobile: {
    paddingTop: 48,
    paddingHorizontal: 24,
    paddingBottom: 32,
  },
  scrollContentWeb: {
    paddingTop: 48,
    paddingHorizontal: 24,
    paddingBottom: 168,
  },

  eyebrow: {
    fontFamily: 'Inter_700Bold',
    fontSize: 11,
    letterSpacing: 4,
    textTransform: 'uppercase',
    color: COLORS.primary,
    marginBottom: 8,
  },
  titleLine1: {
    fontFamily: 'Inter_700Bold',
    fontSize: 42,
    fontWeight: '800',
    lineHeight: 40,
    letterSpacing: -1.5,
    color: COLORS.onSurface,
  },
  titleLine2: {
    fontFamily: 'Inter_700Bold',
    fontSize: 42,
    fontWeight: '800',
    lineHeight: 40,
    letterSpacing: -1.5,
    color: COLORS.tertiary,
    marginBottom: 16,
  },
  heroParagraph: {
    fontFamily: 'Inter_400Regular',
    fontSize: 15,
    lineHeight: 24,
    color: COLORS.onSurfaceVariant,
    maxWidth: 300,
  },
  shapesRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 12,
    marginTop: 24,
    marginBottom: 40,
  },
  shapeCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.primaryContainer,
  },
  shapeRect: {
    width: 32,
    height: 64,
    borderRadius: 8,
    backgroundColor: COLORS.secondaryContainer,
  },
  shapeWide: {
    width: 64,
    height: 32,
    borderRadius: 6,
    backgroundColor: COLORS.tertiaryContainer,
  },
  howToPlayCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 18,
    padding: 18,
    gap: 12,
    shadowColor: '#2F3334',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 3,
  },
  howToPlayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  howToPlayEyebrow: {
    fontFamily: 'Inter_700Bold',
    fontSize: 11,
    letterSpacing: 3,
    textTransform: 'uppercase',
    color: COLORS.primary,
  },
  howToPlayList: {
    gap: 10,
  },
  howToPlayItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    backgroundColor: COLORS.surfaceContainerLow,
    borderRadius: 12,
    padding: 12,
  },
  howToPlayItemContent: {
    flex: 1,
    gap: 2,
  },
  howToPlayItemTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 13,
    letterSpacing: -0.2,
    color: COLORS.onSurface,
    textTransform: 'uppercase',
  },
  howToPlayItemDesc: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.onSurfaceVariant,
  },

  sectionEyebrow: {
    fontFamily: 'Inter_700Bold',
    fontSize: 9,
    letterSpacing: 4,
    textTransform: 'uppercase',
    color: COLORS.primary,
    marginBottom: 6,
  },
  sectionTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 28,
    letterSpacing: -1,
    color: COLORS.onSurface,
    marginBottom: 16,
  },
  sectionBody: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    lineHeight: 23,
    color: COLORS.onSurfaceVariant,
    marginBottom: 8,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: COLORS.outlineVariant,
    opacity: 0.3,
    marginVertical: 36,
  },

  numberedList: {
    gap: 10,
    marginTop: 8,
  },
  numberedItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
    backgroundColor: COLORS.surfaceContainerLow,
    borderRadius: 16,
    padding: 18,
  },
  numberedItemPrimary: {
    backgroundColor: COLORS.surface,
    shadowColor: '#2F3334',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 3,
  },
  itemNumber: {
    fontFamily: 'Inter_700Bold',
    fontSize: 11,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: COLORS.onSurfaceSubtle,
    minWidth: 28,
    marginTop: 2,
  },
  itemContent: {
    flex: 1,
    gap: 3,
  },
  itemLabel: {
    fontFamily: 'Inter_700Bold',
    fontSize: 15,
    letterSpacing: -0.3,
    color: COLORS.onSurface,
    textTransform: 'uppercase',
  },
  itemDesc: {
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    lineHeight: 20,
    color: COLORS.onSurfaceVariant,
  },

  comboGrid: {
    gap: 10,
    marginTop: 8,
  },
  comboRow: {
    flexDirection: 'row',
    gap: 10,
  },
  comboCard: {
    flex: 1,
    backgroundColor: COLORS.surfaceContainerLow,
    borderRadius: 16,
    padding: 16,
    gap: 6,
  },
  comboCardAccent: {
    backgroundColor: COLORS.surface,
    shadowColor: '#2F3334',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 3,
  },
  comboCode: {
    fontFamily: 'Inter_700Bold',
    fontSize: 9,
    letterSpacing: 3,
    textTransform: 'uppercase',
    color: COLORS.onSurfaceSubtle,
  },
  comboLabel: {
    fontFamily: 'Inter_700Bold',
    fontSize: 15,
    letterSpacing: -0.3,
    color: COLORS.onSurface,
  },
  comboDesc: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    lineHeight: 18,
    color: COLORS.onSurfaceVariant,
  },

  callout: {
    backgroundColor: COLORS.primaryContainer,
    borderRadius: 16,
    padding: 20,
    marginTop: 8,
    gap: 8,
  },
  calloutLabel: {
    fontFamily: 'Inter_700Bold',
    fontSize: 12,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: COLORS.primary,
  },
  calloutText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    lineHeight: 22,
    color: COLORS.onSurface,
  },

  footerLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
    opacity: 0.5,
  },
  footerDash: {
    width: 48,
    height: 1,
    backgroundColor: COLORS.outlineVariant,
  },
  footerText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 9,
    letterSpacing: 4,
    textTransform: 'uppercase',
    color: COLORS.onSurfaceVariant,
  },
});
